const data = {
    prducts: [
        {
            _id:'1',
            name:"Nike Air Force 1 '07",
            category:"Women's Shoe",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e777c881-5b62-4250-92a6-362967f54cca/air-force-1-07-womens-shoe-GCkPzr.png',
            price:90,
            brand:'Nike Air Force',
            rating:4.7,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:"Nike Air Force 1 '07",
            category:"Big Kid's Shoe",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d9f1d9ee-a848-4a36-aab9-48b241078ebb/air-force-1-le-big-kids-shoe-3JNSvS.png',
            price:90,
            brand:'Nike Air Force',
            rating:4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:"Nike Air Force 1 '07",
            category:"Men's Shoe",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/air-force-1-07-mens-shoe-5QFp5Z.png',
            price:90,
            brand:'Nike Air Force',
            rating:5.0,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:"Nike Air Force 1 '07",
            category:"Little Kid's Shoe",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ba26a81a-9557-442e-927c-82675cc79f50/force-1-le-little-kids-shoe-d0vJBr.png',
            price:90,
            brand:'Nike Air Force',
            rating:4.0,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:"Nike Air Force 1 Pixel",
            category:"Women's Shoe",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/73809aca-992a-4ae2-a128-ca468ec4e6ae/air-force-1-pixel-womens-shoe-gh10GN.png',
            price:100,
            brand:'Nike Air Force',
            rating:4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:"Nike Air Force 1 Crater",
            category:"Women's Shoe",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/bd1e4b35-7ddc-4678-b1af-13dcf49dbaff/air-force-1-crater-womens-shoe-28NwmB.png',
            price:90,
            brand:'Nike Air Force',
            rating:3.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'7',
            name:"Nike Air Force 1 Crater Flyknit",
            category:"Big Kids' Shoe",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e10be2cf-b248-461f-9ce7-3ef3fdab8cfe/air-force-1-crater-flyknit-big-kids-shoe-LXrWpt.png',
            price:100,
            brand:'Nike Air Force',
            rating:4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'8',
            name:"Nike Air Force 1 '/07",
            category:"Men's Boot",
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f80ac20c-2e2c-4baa-996b-6544f2723d85/air-force-1-mens-boot-rDmRsD.png',
            price:130.97,
            brand:'Nike Air Force',
            rating:4.0,
            numReviews: 10,
            description:'high quality product',
        },
    ]
}

export default data;